### ISSUE TITLE
inference no mask，how to generate point

### ISSUE THREAD

**Issue by LIUTAOGE** [xq141839/SPPNet#2]
if we inference without mask, how to generate point

**Comment by xq141839** [comment]
Hello, for the unseen data, the positive and negative points must be generated manually. Our algorithm aims to help the model learn real sparse information (point) in the practical application instead of automatic point generation.

**Comment by LIUTAOGE** [comment]
> Hello, for the unseen data, the positive and negative points must be generated manually. Our algorithm aims to help the model learn real sparse information (point) in the practical application instead of automatic point generation.


Ok, but I think this does not solve the second problem in the abstract in paper, and it is not helpful for practical applications. It still requires the user to give a display prompt

**Comment by xq141839** [comment]
Compared with SAM, our model only requires one set of positive and negative points. If you use SAM, you will need to input at least 5 sets of P/N points to reach acceptable performance.
