### ISSUE TITLE
How to convert the format of annotation files from png to npy?

### ISSUE THREAD

**Issue by hwj0711** [xq141839/SPPNet#4]

**Comment by hwj0711** [comment]
How to convert the format of annotation files from png to npy?

**Comment by xq141839** [comment]
Hello, feel free to use this [code](https://github.com/CConory/Medical_SAM/blob/Bao/data/MoNuSeg/convert.py) to convert annotation files.

**Comment by hwj0711** [comment]
> 您好，请随意使用此[代码](https://github.com/CConory/Medical_SAM/blob/Bao/data/MoNuSeg/convert.py)转换注释文件。
太感谢啦!!!您的代码写的很棒!!!对我的帮助很大!特别感谢!!!

**Comment by hwj0711** [comment]
我还想请问一下,普通的数据集,image为tif,label为png的数据集,没有实例分割xml标注,用这个项目也能做语义分割吗

**Comment by xq141839** [comment]
也是可以的哦，这个项目本身的目的其实就是做语义分割哒。（你是指息肉那些数据集吗）

**Comment by hwj0711** [comment]
我做的是遥感方面的内容,目前做的是建筑物提取这一块内容,可不可以加个vx或者qq呀

**Comment by xq141839** [comment]
可以的，加我qq好了：1015167278

**Comment by hwj0711** [comment]
好的 谢谢!
